name: CI

on:
  push:
    branches: [ no-py2 ]
  pull_request:
    branches: [ no-py2 ]
  workflow_dispatch:

jobs:
  ci:
    strategy:
      fail-fast: false
      max-parallel: 1
      matrix:
        python-version: [3.9]
        couchdb-version: [3.1]
        #python-version: [3.7, 3.8, 3.9, '3.10']
        #couchdb-version: [1.8, 2.1, 3.1]

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Get poetry
        uses: knowsuchagency/poetry-install@v1
      - name: Set up CouchDB
        uses: iamssen/couchdb-github-action@master
        with:
          couchdb-version: ${{ matrix.couchdb-version }}
        env:
          COUCHDB_USER=admin
          COUCHDB_PASSWORD=password
      - run: poetry install
      - run: poetry run pytest -v --doctest-modules --cov pycouchdb
