name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  ci:
    strategy:
      fail-fast: false
      max-parallel: 3
      matrix:
        python-version: ["3.9", "3.10", "3.11", "3.12", "3.13"]
        couchdb-version: ["2.3", "3.2", "3.3", "3.4", "3.5", "latest"]

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          version: "latest"
      - name: Set up CouchDB
        run: docker run --name couchdb-test-${{ matrix.couchdb-version }} -p 5984:5984 -e COUCHDB_USER=admin -e COUCHDB_PASSWORD=password -d couchdb:${{ matrix.couchdb-version }}
      - run: uv sync --extra dev
      - run: uv run pytest -v ./test/test_integration.py

  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          version: "latest"
      - run: uv sync --extra dev
      - run: uv run pytest -v --doctest-modules --cov pycouchdb ./test/test_functional.py
