name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  # This workflow contains a single job called "build"
  couchdb-integration:
  
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.8, 3.9, 3.10]
        couchdb-version: [1.8, 2.1, 3.1]
        
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Set up CouchDB
        uses: "cobot/couchdb-action@master"
        with:
          couchdb version: ${{ matrix.couchdb-version }}
